(*-----------------------------------------------------------------*)
(*-----------------------------IMPORTS-----------------------------*)
(*-----------------------------------------------------------------*)

#r "FsLexYacc.Runtime.dll"          // Load in FsLexYacc dll

//open System
open Microsoft.FSharp.Text.Lexing   // Lexing Library
open System.IO                      // File Handling

#load "Types.fs"                    // Module with types

#load "ExtWParser.fs"
open ExtWParser                     // Generated Parser from .fsp file

#load "ExtWLexer.fs"
open ExtWLexer                      //Generated Lexer from .fsl file

#load "Parser.fs"                   // Program String -> Statement List
#load "Grapher.fs"                  // Statement List -> Program Graph 

(*-----------------------------------------------------------------*)
(*-------------------CODE-PRE-PROCESSING-MODULE--------------------*)
(*-----------------------------------------------------------------*)

(* File -> Program String *)
let programString : string = File.ReadAllText("Program.extw")

(* Program String -> Statement List *)
let stmtList : Statement list = ParseString programString

(* Statement List -> Program Graph *)
let Edges : Edge list = GraphStatements stmtList
//printfn "%A" Edges


(* Node list generated by Grapher *)
let Nodes : Node list = ExtractNodes Edges
// printfn "%A" Nodes

(* Variable list from Grapher *)
let Variables : Var list = uniqueVars vartemp
// printfn "%A" Variables

(*-----------------------------------------------------------------*)
(*------------------------EXT-DOMAIN-CHECK-------------------------*)
(*-----------------------------------------------------------------*)

// MetaL Parser -> Generate Domain
// Quickchecking domain?

(*-----------------------------------------------------------------*)
(*--------------------------DOMAIN-MODULE--------------------------*)
(*-----------------------------------------------------------------*)

// Pass stuff from DomainGenerator Folder here, and call

#load "LattOps.fs"                   // Lattice Opreations: Union, Intersection, Subset, Superset
#load "Domain.fs"                   // Domain Specification: Generated code and call traces for LattOps

(*-----------------------------------------------------------------*)
(*---------------------TRANSFER-FUNCTION-MODULE--------------------*)
(*-----------------------------------------------------------------*)

#load "TransferFunctions.fs"        // Transfer Function Specification + 
                                    // Direction, combination op, iota, init

(*                          QuickChecking                          *)
//insert QuickChecking folder stuff here

(*-----------------------------------------------------------------*)
(*-------------------------ANALYSIS-MODULE-------------------------*)
(*-----------------------------------------------------------------*)

#load "Analysis.fs"                 // Program Graph -> Analysis Result

// Program Graph -> Analysis Result
let Analysis : AnalysisResult = AnalyseEdges Edges // union/intersection function, sub/super -seteq function as parameters


(*-----------------------------------------------------------------*)
(*-----------------------------RESULTS-----------------------------*)
(*-----------------------------------------------------------------*)

let format text (chars:string) =
    Array.fold (
        fun (s:string) c -> s.Replace(c.ToString(),"").Replace("};", "};\n\t\t")
    ) text (chars.ToCharArray())

printfn "RESULT:"
Analysis |> Seq.iter (fun x -> (printfn "%A\t->\t%s" x.Key (format (x.Value.ToString()) "\n")); printfn "\n")