// Implementation file for parser generated by fsyacc
module MetaLParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 ".\MetaLParser.fsp"

open System
open DomainTypes



# 13 ".\MetaLParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | INTSET
  | STRSET
  | POWERSET
  | LBRA
  | RBRA
  | TFS
  | CART
  | LSQ
  | RSQ
  | UNION
  | LCURL
  | RCURL
  | SCOL
  | EOF
  | IDENTSET
  | VARSET
  | ARRSET
  | QSET
  | ELEM of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_INTSET
    | TOKEN_STRSET
    | TOKEN_POWERSET
    | TOKEN_LBRA
    | TOKEN_RBRA
    | TOKEN_TFS
    | TOKEN_CART
    | TOKEN_LSQ
    | TOKEN_RSQ
    | TOKEN_UNION
    | TOKEN_LCURL
    | TOKEN_RCURL
    | TOKEN_SCOL
    | TOKEN_EOF
    | TOKEN_IDENTSET
    | TOKEN_VARSET
    | TOKEN_ARRSET
    | TOKEN_QSET
    | TOKEN_ELEM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_domain
    | NONTERM_dinst
    | NONTERM_sset
    | NONTERM_set
    | NONTERM_elist

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | INTSET  -> 0 
  | STRSET  -> 1 
  | POWERSET  -> 2 
  | LBRA  -> 3 
  | RBRA  -> 4 
  | TFS  -> 5 
  | CART  -> 6 
  | LSQ  -> 7 
  | RSQ  -> 8 
  | UNION  -> 9 
  | LCURL  -> 10 
  | RCURL  -> 11 
  | SCOL  -> 12 
  | EOF  -> 13 
  | IDENTSET  -> 14 
  | VARSET  -> 15 
  | ARRSET  -> 16 
  | QSET  -> 17 
  | ELEM _ -> 18 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_INTSET 
  | 1 -> TOKEN_STRSET 
  | 2 -> TOKEN_POWERSET 
  | 3 -> TOKEN_LBRA 
  | 4 -> TOKEN_RBRA 
  | 5 -> TOKEN_TFS 
  | 6 -> TOKEN_CART 
  | 7 -> TOKEN_LSQ 
  | 8 -> TOKEN_RSQ 
  | 9 -> TOKEN_UNION 
  | 10 -> TOKEN_LCURL 
  | 11 -> TOKEN_RCURL 
  | 12 -> TOKEN_SCOL 
  | 13 -> TOKEN_EOF 
  | 14 -> TOKEN_IDENTSET 
  | 15 -> TOKEN_VARSET 
  | 16 -> TOKEN_ARRSET 
  | 17 -> TOKEN_QSET 
  | 18 -> TOKEN_ELEM 
  | 21 -> TOKEN_end_of_input
  | 19 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_domain 
    | 3 -> NONTERM_domain 
    | 4 -> NONTERM_dinst 
    | 5 -> NONTERM_dinst 
    | 6 -> NONTERM_dinst 
    | 7 -> NONTERM_sset 
    | 8 -> NONTERM_sset 
    | 9 -> NONTERM_sset 
    | 10 -> NONTERM_sset 
    | 11 -> NONTERM_set 
    | 12 -> NONTERM_set 
    | 13 -> NONTERM_set 
    | 14 -> NONTERM_set 
    | 15 -> NONTERM_set 
    | 16 -> NONTERM_set 
    | 17 -> NONTERM_set 
    | 18 -> NONTERM_set 
    | 19 -> NONTERM_elist 
    | 20 -> NONTERM_elist 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 21 
let _fsyacc_tagOfErrorTerminal = 19

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | INTSET  -> "INTSET" 
  | STRSET  -> "STRSET" 
  | POWERSET  -> "POWERSET" 
  | LBRA  -> "LBRA" 
  | RBRA  -> "RBRA" 
  | TFS  -> "TFS" 
  | CART  -> "CART" 
  | LSQ  -> "LSQ" 
  | RSQ  -> "RSQ" 
  | UNION  -> "UNION" 
  | LCURL  -> "LCURL" 
  | RCURL  -> "RCURL" 
  | SCOL  -> "SCOL" 
  | EOF  -> "EOF" 
  | IDENTSET  -> "IDENTSET" 
  | VARSET  -> "VARSET" 
  | ARRSET  -> "ARRSET" 
  | QSET  -> "QSET" 
  | ELEM _ -> "ELEM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | INTSET  -> (null : System.Object) 
  | STRSET  -> (null : System.Object) 
  | POWERSET  -> (null : System.Object) 
  | LBRA  -> (null : System.Object) 
  | RBRA  -> (null : System.Object) 
  | TFS  -> (null : System.Object) 
  | CART  -> (null : System.Object) 
  | LSQ  -> (null : System.Object) 
  | RSQ  -> (null : System.Object) 
  | UNION  -> (null : System.Object) 
  | LCURL  -> (null : System.Object) 
  | RCURL  -> (null : System.Object) 
  | SCOL  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | IDENTSET  -> (null : System.Object) 
  | VARSET  -> (null : System.Object) 
  | ARRSET  -> (null : System.Object) 
  | QSET  -> (null : System.Object) 
  | ELEM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 3us; 65535us; 0us; 4us; 5us; 6us; 13us; 14us; 7us; 65535us; 8us; 22us; 11us; 12us; 29us; 22us; 30us; 23us; 31us; 22us; 33us; 22us; 41us; 22us; 7us; 65535us; 8us; 9us; 11us; 16us; 29us; 24us; 30us; 26us; 31us; 25us; 33us; 27us; 41us; 28us; 2us; 65535us; 35us; 36us; 44us; 45us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 9us; 17us; 25us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 3us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 2us; 4us; 12us; 1us; 4us; 2us; 5us; 6us; 2us; 5us; 11us; 1us; 5us; 1us; 5us; 1us; 5us; 2us; 6us; 12us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 2us; 11us; 13us; 2us; 12us; 12us; 2us; 12us; 13us; 2us; 12us; 14us; 2us; 12us; 14us; 2us; 12us; 18us; 1us; 12us; 2us; 13us; 14us; 1us; 13us; 1us; 13us; 1us; 14us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 15us; 1us; 16us; 1us; 17us; 1us; 18us; 1us; 18us; 1us; 18us; 2us; 19us; 20us; 1us; 20us; 1us; 20us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 9us; 11us; 13us; 15us; 17us; 19us; 22us; 24us; 27us; 30us; 32us; 34us; 36us; 39us; 41us; 43us; 45us; 47us; 49us; 51us; 54us; 57us; 60us; 63us; 66us; 69us; 71us; 74us; 76us; 78us; 80us; 82us; 84us; 86us; 88us; 90us; 92us; 94us; 96us; 98us; 101us; 103us; |]
let _fsyacc_action_rows = 46
let _fsyacc_actionTableElements = [|2us; 32768us; 2us; 7us; 7us; 11us; 0us; 49152us; 2us; 32768us; 6us; 5us; 13us; 3us; 0us; 16385us; 0us; 16386us; 2us; 32768us; 2us; 7us; 7us; 11us; 0us; 16387us; 1us; 32768us; 3us; 8us; 9us; 32768us; 0us; 38us; 1us; 39us; 2us; 40us; 7us; 30us; 10us; 35us; 14us; 20us; 15us; 18us; 16us; 19us; 17us; 21us; 2us; 32768us; 4us; 10us; 6us; 29us; 0us; 16388us; 9us; 32768us; 0us; 38us; 1us; 39us; 2us; 40us; 7us; 30us; 10us; 35us; 14us; 20us; 15us; 18us; 16us; 19us; 17us; 21us; 1us; 16395us; 5us; 13us; 2us; 32768us; 2us; 7us; 7us; 11us; 1us; 32768us; 8us; 15us; 0us; 16389us; 2us; 32768us; 6us; 29us; 8us; 17us; 0us; 16390us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 1us; 16395us; 5us; 31us; 0us; 16396us; 2us; 32768us; 6us; 29us; 8us; 32us; 2us; 32768us; 6us; 29us; 9us; 33us; 2us; 32768us; 6us; 29us; 8us; 34us; 2us; 32768us; 4us; 42us; 6us; 29us; 9us; 32768us; 0us; 38us; 1us; 39us; 2us; 40us; 7us; 30us; 10us; 35us; 14us; 20us; 15us; 18us; 16us; 19us; 17us; 21us; 9us; 32768us; 0us; 38us; 1us; 39us; 2us; 40us; 7us; 30us; 10us; 35us; 14us; 20us; 15us; 18us; 16us; 19us; 17us; 21us; 9us; 32768us; 0us; 38us; 1us; 39us; 2us; 40us; 7us; 30us; 10us; 35us; 14us; 20us; 15us; 18us; 16us; 19us; 17us; 21us; 0us; 16397us; 9us; 32768us; 0us; 38us; 1us; 39us; 2us; 40us; 7us; 30us; 10us; 35us; 14us; 20us; 15us; 18us; 16us; 19us; 17us; 21us; 0us; 16398us; 1us; 32768us; 18us; 43us; 1us; 32768us; 11us; 37us; 0us; 16399us; 0us; 16400us; 0us; 16401us; 1us; 32768us; 3us; 41us; 9us; 32768us; 0us; 38us; 1us; 39us; 2us; 40us; 7us; 30us; 10us; 35us; 14us; 20us; 15us; 18us; 16us; 19us; 17us; 21us; 0us; 16402us; 1us; 16403us; 12us; 44us; 1us; 32768us; 18us; 43us; 0us; 16404us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 7us; 8us; 9us; 12us; 13us; 15us; 25us; 28us; 29us; 39us; 41us; 44us; 46us; 47us; 50us; 51us; 52us; 53us; 54us; 55us; 56us; 58us; 59us; 62us; 65us; 68us; 71us; 81us; 91us; 101us; 102us; 112us; 113us; 115us; 117us; 118us; 119us; 120us; 122us; 132us; 133us; 135us; 137us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 3us; 4us; 5us; 3us; 1us; 1us; 1us; 1us; 1us; 3us; 5us; 5us; 3us; 1us; 1us; 4us; 1us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 3us; 4us; 4us; 4us; 4us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 5us; 6us; 6us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 65535us; 16387us; 65535us; 65535us; 65535us; 16388us; 65535us; 65535us; 65535us; 65535us; 16389us; 65535us; 16390us; 16391us; 16392us; 16393us; 16394us; 16395us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16397us; 65535us; 16398us; 65535us; 65535us; 16399us; 16400us; 16401us; 65535us; 65535us; 16402us; 65535us; 65535us; 16404us; |]
let _fsyacc_reductions ()  =    [| 
# 202 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : domain)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 211 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'domain)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 ".\MetaLParser.fsp"
                                                                  _1 
                   )
# 25 ".\MetaLParser.fsp"
                 : domain));
# 222 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'dinst)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 ".\MetaLParser.fsp"
                                                               _1 
                   )
# 28 ".\MetaLParser.fsp"
                 : 'domain));
# 233 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'domain)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'dinst)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 ".\MetaLParser.fsp"
                                                               CartesianDom(_1,_3) 
                   )
# 29 ".\MetaLParser.fsp"
                 : 'domain));
# 245 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 ".\MetaLParser.fsp"
                                                               PowersetDom(_3) 
                   )
# 32 ".\MetaLParser.fsp"
                 : 'dinst));
# 256 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'sset)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'dinst)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 ".\MetaLParser.fsp"
                                                               TotalFunctionSpaceDom(_2,_4) 
                   )
# 33 ".\MetaLParser.fsp"
                 : 'dinst));
# 268 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 ".\MetaLParser.fsp"
                                                               SetDom(_2) 
                   )
# 34 ".\MetaLParser.fsp"
                 : 'dinst));
# 279 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 ".\MetaLParser.fsp"
                                                               VARSet 
                   )
# 37 ".\MetaLParser.fsp"
                 : 'sset));
# 289 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 ".\MetaLParser.fsp"
                                                               ARRSet 
                   )
# 38 ".\MetaLParser.fsp"
                 : 'sset));
# 299 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 ".\MetaLParser.fsp"
                                                               IDENTSet 
                   )
# 39 ".\MetaLParser.fsp"
                 : 'sset));
# 309 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 ".\MetaLParser.fsp"
                                                               QSet 
                   )
# 40 ".\MetaLParser.fsp"
                 : 'sset));
# 319 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'sset)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 ".\MetaLParser.fsp"
                                                               SsetSet(_1) 
                   )
# 43 ".\MetaLParser.fsp"
                 : 'set));
# 330 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 ".\MetaLParser.fsp"
                                                               CartesianSet(_1,_3) 
                   )
# 44 ".\MetaLParser.fsp"
                 : 'set));
# 342 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'sset)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 ".\MetaLParser.fsp"
                                                               TotalFunctionSpaceSet(_2,_4) 
                   )
# 45 ".\MetaLParser.fsp"
                 : 'set));
# 354 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 ".\MetaLParser.fsp"
                                                               UnionSet(_2,_4) 
                   )
# 46 ".\MetaLParser.fsp"
                 : 'set));
# 366 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'elist)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 ".\MetaLParser.fsp"
                                                               ListSet(_2) 
                   )
# 47 ".\MetaLParser.fsp"
                 : 'set));
# 377 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 ".\MetaLParser.fsp"
                                                               INTSet 
                   )
# 48 ".\MetaLParser.fsp"
                 : 'set));
# 387 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 ".\MetaLParser.fsp"
                                                               STRSet 
                   )
# 49 ".\MetaLParser.fsp"
                 : 'set));
# 397 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 ".\MetaLParser.fsp"
                                                               PowersetSet(_3) 
                   )
# 50 ".\MetaLParser.fsp"
                 : 'set));
# 408 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 ".\MetaLParser.fsp"
                                                               Element(_1) 
                   )
# 53 ".\MetaLParser.fsp"
                 : 'elist));
# 419 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'elist)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 ".\MetaLParser.fsp"
                                                               LargerList(_1,_3) 
                   )
# 54 ".\MetaLParser.fsp"
                 : 'elist));
|]
# 432 ".\MetaLParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 22;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : domain =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
