// Implementation file for parser generated by fsyacc
module MetaLParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 ".\MetaLParser.fsp"

open System
open DomainTypes



# 13 ".\MetaLParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | POWERSET
  | LBRA
  | RBRA
  | TFS
  | CART
  | VARSET
  | QSET
  | LSQ
  | RSQ
  | UNION
  | LCURL
  | RCURL
  | SCOL
  | EOF
  | ARRSET
  | ELEM of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_POWERSET
    | TOKEN_LBRA
    | TOKEN_RBRA
    | TOKEN_TFS
    | TOKEN_CART
    | TOKEN_VARSET
    | TOKEN_QSET
    | TOKEN_LSQ
    | TOKEN_RSQ
    | TOKEN_UNION
    | TOKEN_LCURL
    | TOKEN_RCURL
    | TOKEN_SCOL
    | TOKEN_EOF
    | TOKEN_ARRSET
    | TOKEN_ELEM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_domainc
    | NONTERM_domain
    | NONTERM_set
    | NONTERM_elist

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | POWERSET  -> 0 
  | LBRA  -> 1 
  | RBRA  -> 2 
  | TFS  -> 3 
  | CART  -> 4 
  | VARSET  -> 5 
  | QSET  -> 6 
  | LSQ  -> 7 
  | RSQ  -> 8 
  | UNION  -> 9 
  | LCURL  -> 10 
  | RCURL  -> 11 
  | SCOL  -> 12 
  | EOF  -> 13 
  | ARRSET  -> 14 
  | ELEM _ -> 15 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_POWERSET 
  | 1 -> TOKEN_LBRA 
  | 2 -> TOKEN_RBRA 
  | 3 -> TOKEN_TFS 
  | 4 -> TOKEN_CART 
  | 5 -> TOKEN_VARSET 
  | 6 -> TOKEN_QSET 
  | 7 -> TOKEN_LSQ 
  | 8 -> TOKEN_RSQ 
  | 9 -> TOKEN_UNION 
  | 10 -> TOKEN_LCURL 
  | 11 -> TOKEN_RCURL 
  | 12 -> TOKEN_SCOL 
  | 13 -> TOKEN_EOF 
  | 14 -> TOKEN_ARRSET 
  | 15 -> TOKEN_ELEM 
  | 18 -> TOKEN_end_of_input
  | 16 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_domainc 
    | 3 -> NONTERM_domainc 
    | 4 -> NONTERM_domain 
    | 5 -> NONTERM_domain 
    | 6 -> NONTERM_set 
    | 7 -> NONTERM_set 
    | 8 -> NONTERM_set 
    | 9 -> NONTERM_set 
    | 10 -> NONTERM_set 
    | 11 -> NONTERM_set 
    | 12 -> NONTERM_set 
    | 13 -> NONTERM_set 
    | 14 -> NONTERM_elist 
    | 15 -> NONTERM_elist 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 18 
let _fsyacc_tagOfErrorTerminal = 16

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | POWERSET  -> "POWERSET" 
  | LBRA  -> "LBRA" 
  | RBRA  -> "RBRA" 
  | TFS  -> "TFS" 
  | CART  -> "CART" 
  | VARSET  -> "VARSET" 
  | QSET  -> "QSET" 
  | LSQ  -> "LSQ" 
  | RSQ  -> "RSQ" 
  | UNION  -> "UNION" 
  | LCURL  -> "LCURL" 
  | RCURL  -> "RCURL" 
  | SCOL  -> "SCOL" 
  | EOF  -> "EOF" 
  | ARRSET  -> "ARRSET" 
  | ELEM _ -> "ELEM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | POWERSET  -> (null : System.Object) 
  | LBRA  -> (null : System.Object) 
  | RBRA  -> (null : System.Object) 
  | TFS  -> (null : System.Object) 
  | CART  -> (null : System.Object) 
  | VARSET  -> (null : System.Object) 
  | QSET  -> (null : System.Object) 
  | LSQ  -> (null : System.Object) 
  | RSQ  -> (null : System.Object) 
  | UNION  -> (null : System.Object) 
  | LCURL  -> (null : System.Object) 
  | RCURL  -> (null : System.Object) 
  | SCOL  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | ARRSET  -> (null : System.Object) 
  | ELEM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 3us; 65535us; 0us; 4us; 5us; 6us; 13us; 14us; 7us; 65535us; 8us; 9us; 11us; 12us; 21us; 16us; 25us; 17us; 26us; 18us; 32us; 19us; 34us; 20us; 2us; 65535us; 28us; 29us; 37us; 38us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 9us; 17us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 3us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 2us; 4us; 6us; 1us; 4us; 1us; 5us; 2us; 5us; 6us; 1us; 5us; 1us; 5us; 1us; 5us; 2us; 6us; 6us; 3us; 6us; 10us; 13us; 2us; 6us; 10us; 2us; 6us; 12us; 2us; 6us; 13us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 2us; 10us; 13us; 1us; 10us; 1us; 10us; 1us; 11us; 1us; 11us; 1us; 11us; 1us; 12us; 1us; 12us; 1us; 12us; 1us; 13us; 1us; 13us; 2us; 14us; 15us; 1us; 15us; 1us; 15us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 9us; 11us; 13us; 15us; 17us; 19us; 22us; 24us; 26us; 29us; 31us; 33us; 35us; 38us; 42us; 45us; 48us; 51us; 53us; 55us; 57us; 59us; 62us; 64us; 66us; 68us; 70us; 72us; 74us; 76us; 78us; 80us; 82us; 85us; 87us; |]
let _fsyacc_action_rows = 39
let _fsyacc_actionTableElements = [|2us; 32768us; 0us; 7us; 7us; 11us; 0us; 49152us; 2us; 32768us; 4us; 5us; 13us; 3us; 0us; 16385us; 0us; 16386us; 2us; 32768us; 0us; 7us; 7us; 11us; 0us; 16387us; 1us; 32768us; 1us; 8us; 6us; 32768us; 0us; 31us; 5us; 22us; 6us; 24us; 7us; 25us; 10us; 28us; 14us; 23us; 2us; 32768us; 2us; 10us; 4us; 21us; 0us; 16388us; 6us; 32768us; 0us; 31us; 5us; 22us; 6us; 24us; 7us; 25us; 10us; 28us; 14us; 23us; 2us; 32768us; 3us; 13us; 4us; 21us; 2us; 32768us; 0us; 7us; 7us; 11us; 1us; 32768us; 8us; 15us; 0us; 16389us; 0us; 16390us; 3us; 32768us; 3us; 34us; 4us; 21us; 9us; 26us; 2us; 32768us; 4us; 21us; 8us; 27us; 2us; 32768us; 2us; 33us; 4us; 21us; 2us; 32768us; 4us; 21us; 8us; 35us; 6us; 32768us; 0us; 31us; 5us; 22us; 6us; 24us; 7us; 25us; 10us; 28us; 14us; 23us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 6us; 32768us; 0us; 31us; 5us; 22us; 6us; 24us; 7us; 25us; 10us; 28us; 14us; 23us; 6us; 32768us; 0us; 31us; 5us; 22us; 6us; 24us; 7us; 25us; 10us; 28us; 14us; 23us; 0us; 16394us; 1us; 32768us; 15us; 36us; 1us; 32768us; 11us; 30us; 0us; 16395us; 1us; 32768us; 1us; 32us; 6us; 32768us; 0us; 31us; 5us; 22us; 6us; 24us; 7us; 25us; 10us; 28us; 14us; 23us; 0us; 16396us; 6us; 32768us; 0us; 31us; 5us; 22us; 6us; 24us; 7us; 25us; 10us; 28us; 14us; 23us; 0us; 16397us; 1us; 16398us; 12us; 37us; 1us; 32768us; 15us; 36us; 0us; 16399us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 7us; 8us; 9us; 12us; 13us; 15us; 22us; 25us; 26us; 33us; 36us; 39us; 41us; 42us; 43us; 47us; 50us; 53us; 56us; 63us; 64us; 65us; 66us; 73us; 80us; 81us; 83us; 85us; 86us; 88us; 95us; 96us; 103us; 104us; 106us; 108us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 3us; 4us; 5us; 3us; 1us; 1us; 1us; 5us; 3us; 4us; 5us; 1us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 4us; 4us; 4us; 4us; 4us; 4us; 4us; 4us; 5us; 5us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 65535us; 16387us; 65535us; 65535us; 65535us; 16388us; 65535us; 65535us; 65535us; 65535us; 16389us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16391us; 16392us; 16393us; 65535us; 65535us; 16394us; 65535us; 65535us; 16395us; 65535us; 65535us; 16396us; 65535us; 16397us; 65535us; 65535us; 16399us; |]
let _fsyacc_reductions ()  =    [| 
# 178 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : domain)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 187 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'domainc)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 ".\MetaLParser.fsp"
                                              _1
                   )
# 21 ".\MetaLParser.fsp"
                 : domain));
# 198 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'domain)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 ".\MetaLParser.fsp"
                                                              _1
                   )
# 24 ".\MetaLParser.fsp"
                 : 'domainc));
# 209 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'domainc)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'domain)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 ".\MetaLParser.fsp"
                                                               CartesianDom(_1,_3) 
                   )
# 25 ".\MetaLParser.fsp"
                 : 'domainc));
# 221 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 ".\MetaLParser.fsp"
                                                               PowersetDom(_3) 
                   )
# 28 ".\MetaLParser.fsp"
                 : 'domain));
# 232 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'domain)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 ".\MetaLParser.fsp"
                                                               TotalFunctionSpaceDom(_2,_4) 
                   )
# 29 ".\MetaLParser.fsp"
                 : 'domain));
# 244 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 ".\MetaLParser.fsp"
                                                               CartesianSet(_1,_3) 
                   )
# 32 ".\MetaLParser.fsp"
                 : 'set));
# 256 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 ".\MetaLParser.fsp"
                                                               VARSet 
                   )
# 33 ".\MetaLParser.fsp"
                 : 'set));
# 266 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 ".\MetaLParser.fsp"
                                                               ARRSet 
                   )
# 34 ".\MetaLParser.fsp"
                 : 'set));
# 276 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 ".\MetaLParser.fsp"
                                                               QSet 
                   )
# 35 ".\MetaLParser.fsp"
                 : 'set));
# 286 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 ".\MetaLParser.fsp"
                                                               UnionSet(_2,_4) 
                   )
# 36 ".\MetaLParser.fsp"
                 : 'set));
# 298 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'elist)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 ".\MetaLParser.fsp"
                                                               ListSet(_2) 
                   )
# 37 ".\MetaLParser.fsp"
                 : 'set));
# 309 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 ".\MetaLParser.fsp"
                                                               PowersetSet(_3) 
                   )
# 38 ".\MetaLParser.fsp"
                 : 'set));
# 320 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'set)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 ".\MetaLParser.fsp"
                                                              TotalFunctionSpaceSet(_2,_4)
                   )
# 39 ".\MetaLParser.fsp"
                 : 'set));
# 332 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 ".\MetaLParser.fsp"
                                                               Element(_1) 
                   )
# 42 ".\MetaLParser.fsp"
                 : 'elist));
# 343 ".\MetaLParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'elist)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 ".\MetaLParser.fsp"
                                                               LargerList(_1,_3) 
                   )
# 43 ".\MetaLParser.fsp"
                 : 'elist));
|]
# 356 ".\MetaLParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 19;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : domain =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
